// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6lX86L-187TyfrpdixadwnxStaS_77kg',
    appId: '1:747273259281:web:ad8476434e07037a0164b0',
    messagingSenderId: '747273259281',
    projectId: 'chat-app-b4b4c',
    authDomain: 'chat-app-b4b4c.firebaseapp.com',
    storageBucket: 'chat-app-b4b4c.firebasestorage.app',
    measurementId: 'G-NTT3DYFKWW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyOBvuADQK0VJe9Ojwqnyta99HOb6z1XI',
    appId: '1:747273259281:android:12afb06b3e879e1d0164b0',
    messagingSenderId: '747273259281',
    projectId: 'chat-app-b4b4c',
    storageBucket: 'chat-app-b4b4c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8GdYHm8WWrst6Bo8vF6iCr7Nvl2-pV4Y',
    appId: '1:747273259281:ios:a91240df3b5ec4500164b0',
    messagingSenderId: '747273259281',
    projectId: 'chat-app-b4b4c',
    storageBucket: 'chat-app-b4b4c.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8GdYHm8WWrst6Bo8vF6iCr7Nvl2-pV4Y',
    appId: '1:747273259281:ios:a91240df3b5ec4500164b0',
    messagingSenderId: '747273259281',
    projectId: 'chat-app-b4b4c',
    storageBucket: 'chat-app-b4b4c.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6lX86L-187TyfrpdixadwnxStaS_77kg',
    appId: '1:747273259281:web:f7fe440e87bbf13e0164b0',
    messagingSenderId: '747273259281',
    projectId: 'chat-app-b4b4c',
    authDomain: 'chat-app-b4b4c.firebaseapp.com',
    storageBucket: 'chat-app-b4b4c.firebasestorage.app',
    measurementId: 'G-55FMX65FR4',
  );
}
